#!/bin/sh
echo "This script compiles, installs and starts GNUnet."
echo "It must be run as root (sorry)."
echo "GNUnet will be installed to /usr/local/."
echo "Configuration files are created in /etc/gnunetd.conf."
echo "Users still have to run gnunet-setup to create their"
echo "personal configuration file ($USER/gnunet.conf)."
echo "An init-script will be placed under /etc/init.d/gnunetd"
echo " "
if test $USER != root
then 
  echo "Not root.  Aborting."
  exit -1
fi
if test -f contrib/initgnunet
then
 echo "Please press CTRL-C now to abort or RETURN to continue."
 read
else
 echo "This script must be run from the GNUnet/ source directory."
 exit -1
fi
cp contrib/initgnunet /etc/init.d/gnunetd
chmod +x /etc/init.d/gnunetd
./configure --prefix=/usr/local
make -s
make -s install
echo " "
echo "Press RETURN to start the interactive setup tool."
read
/usr/local/bin/gnunet-setup -d || exit -1
echo " "
echo "Note that you can start GNUnet text-user interfaces"
echo "with the commands "
echo " "
echo "$ /usr/local/bin/gnunet-search"
echo "$ /usr/local/bin/gnunet-download"
echo "$ /usr/local/bin/gnunet-insert"
echo " "
echo "You may want to edit your startup sequence to"
echo "automatically start gnunetd whenever your system boots."
echo " "
echo "Visit http://gnunet.org/ for further information."
echo " "
echo "Press RETURN to run gnunet-update and then start gnunetd."
read
/usr/local/bin/gnunet-update
/usr/local/bin/gnunetd
