#!/bin/sh
cd /tmp
rm -rf GNUnet*
echo "Checking out GNUnet from the pserver"
cvs -d :pserver:anonymous@ovmj.org:/var/cvs/GNUnet checkout GNUnet
cd GNUnet
./bootstrap
./configure
make dist
cp GNUnet-*.tar.* /usr/src/redhat/SOURCES
cp GNUnet-*.tar.* /tmp/upload
cp contrib/gnunet.spec /usr/src/redhat/SPECS
cd /usr/src/redhat/SPECS
rpm -ba gnunet.spec
cd ../SRPMS
cp GNUnet-$1*.src.rpm /tmp/upload
cd ../RPMS/i386
cp GNUnet-$1*.rpm /tmp/upload
cd /tmp/upload
echo "/tmp/upload now contains the files to upload."
