#!/bin/sh
TOTAL=`grep "forwarding query" $1 | wc -l`
DISTINCT=`grep "forwarding query" $1 | awk '{ print $8 }' | sort | uniq | wc -l`
PERCENT=`expr $DISTINCT \* 100 / $TOTAL`
echo "Forwarded $DISTINCT distinct queries out of a total of $TOTAL ($PERCENT%)."
echo " "
echo "Frequencies plotted."
grep "forwarding query" $1 | awk '{ print $8 }' | sort | uniq -c | awk '{ print $1 }' | sort | uniq -c | awk '{ print $2 " " $1 }' | sort -g > /tmp/plot
gnuplot << EOF
set terminal postscript
set output 'graph.ps'
set xlabel 'frequency query forwarded'
set ylabel 'number of queries with this frequency'
set xr [0:]
set yr [0:]
plot "/tmp/plot" with points
EOF
gv graph.ps &
