#!/bin/sh
export WANT_AUTOMAKE="1.8"
export MKDIR_P="mkdir -p"

if test "$(which automake-1.8)" != ""; then
	export AUTOMAKE="automake-1.8"
elif test "$(which automake)" != ""; then
	export AUTOMAKE="automake"
else
	echo "Error: automake not found"
	exit
fi

if test "$(which aclocal-1.8)" != ""; then
	export ACLOCAL="aclocal-1.8"
elif test "$(which aclocal)" != ""; then
	export ACLOCAL="aclocal"
else
	echo "Error: aclocal not found"
	exit
fi

$AUTOMAKE -fi
cd libltdl
autoreconf -f -i
cd ..
autoreconf -f -i
