#!/bin/sh
# Convert an ASCII file into C code that outputs
# that ASCII file (converts " to \" and puts
# fprintf and a function around the file).
echo "#include <stdio.h>"
echo "#include <unistd.h>"
echo "void " $2 "(FILE * f) {"
#if [ $2 = 'generate_gnunetd_conf' ]
#then
# echo " if (access(\"/var/lib/GNUnet\", X_OK))";
# echo "  fprintf(f, \"GNUNETD_HOME = ~/.gnunet\\n\");";
# echo " else";
# echo "  fprintf(f, \"GNUNETD_HOME = /var/lib/GNUnet\\n\");";
#fi
cat $1 | sed \
        -e "s/\"/\\\\\"/g" \
	-e "s/^/ fprintf(f, \"%s\\\\n\",\"/" \
        -e "s/$/\");/"
echo "}";