.TH GNUNET-PEER-INFO 1 "April 30, 2005" "GNUnet"

.SH NAME
gnunet\-peer\-info \- Display information about other known nodes.

.SH SYNOPSIS
.B gnunet\-peer\-info
.RI [ options ]
.br

.SH DESCRIPTION
.PP
\fBgnunet\-peer\-info\fP display the last known IP and GNUnet host address of known nodes.

.SH OPTIONS
.B
.IP "\-h, \-\-help"
Print help page
.B
.IP "\-c FILENAME, \-\-config=FILENAME"
Load config file (default: /etc/gnunet.conf)
.B
.IP "\-v, \-\-version"
Print the version number
.B
.IP "\-L LOGLEVEL, \-\-loglelvel=LOGLEVEL"
Set the loglevel

.SH BUGS
Report bugs by using mantis <https://gnunet.org/mantis/> or by sending electronic mail to <gnunet\-developers@gnu.org>

.SH SEE ALSO
gnunetd.conf(5), gnunetd(1)
