.TH GNUNET-STATS 1 "May 20, 2006" "GNUnet"

.SH NAME
gnunet-stats \- Display statistics about your GNUnet server.

.SH SYNOPSIS
.B gnunet-stats
.RI [ options ]
.br

.SH DESCRIPTION
\fBgnunet\-stats\fP is used to display detailed information about various aspect of gnunetd's operation.  This tool only works if the "stats" module is loaded by gnunetd.

.SH OPTIONS

.TP
.IP "\-c FILENAME,  \-\-config=FILENAME"
load config file

.TP
.IP "\-h, \-\-help"
print this page

.TP
.IP "\-H HOSTNAME, \-\-host=HOSTNAME"
on which host is gnunetd running (default: localhost).  You can also specify a port using the syntax HOSTNAME:PORT.  The default port is 2087.

.TP
.IP "\-L LOGLEVEL, \-\-loglevel=LOGLEVEL"
set the loglevel

.TP
.IP "\-p,  \-\-protocols"
print supported protocol messages

.TP
.IP "\-v, \-\-version"
print version number


.SH BUGS
Report bugs by using mantis <https://gnunet.org/mantis/> or by sending electronic mail to <gnunet-developers@gnu.org>

.SH SEE ALSO
gnunetd.conf(5), gnunet.conf(5), gnunetd(1)
