.TH GNUNET-AUTO-SHARE "1" "17 Feb 2008" "GNUnet"
.SH NAME
gnunet\-auto\-share \- process to share a directory
.SH SYNOPSIS
.B gnunet\-auto\-share
[\fIOPTIONS\fR] DIRECTORY
.SH DESCRIPTION
.PP
In order to share files with other GNUnet users, the files must first
be made available to GNUnet.  This tool allows you to automatically
share all files from a certain directory.
.PP
In order to start sharing files, invoke gnunet-auto-share with the
name of the directory.  As long as gnunet-auto-share is running, any
files placed in the directory will be automatically shared.  
Note that files that you share may not always continue to be
available after you leave the network.
.PP
gnunet\-auto\-share will automatically extract keywords from the files that
are shared.  Users that want to download files from GNUnet use
keywords to search for the appropriate content.  You can manually add keywords
using the \-K option.
.PP
The directory structure of files in the shared directory will be 
maintained.  gnunet\-auto\-share only supports publishing files
using indexing.  Indexing a file means that an index is
added to the local (!)  database with symbolic links to the file
itself.  The links will use the SHA-512 hash of the entire file as the
filename.  Indexing is generally significantly more efficient and the
default choice.  However, indexing only works if the indexed file can
be read (using the same absolute path) by gnunetd, so you should
run gnunet\-auto\-share on the same machine that uses gnunetd.
.PP
You can add metadata for the shared files by specifying metadata in
a metadata configuration file (by default located in 
~/.gnunet/metadata.conf).  The format of this file is just like
the normal GNUnet configuration files.  Each section name should
correspond to a filename in the directory.  The keys are the 
various metadata types and the entries correspond to the metadata
values.  The special type "keyword" can be used to specify a list
of keywords that should be used for the respective file.  Multiple
keywords should be separated by "AND".  Example:

 [COPYING]
 title = "The GNU Public License"
 copyright = "1989, 1991 Free Software Foundation, Inc."
 version = "2"
 date = "June 1991"
 mimetype = "text/plain"
 description = "The most frequently used free software license"
 language = "English"
 organization = "Free Software Foundation"
 keywords = "GPL AND GNU AND free AND license AND public AND FSF AND test"
 
 [gnunet-logo.svg]
 title = "Official logo of teh GNUnet project"
 description = "Combines the GNU logo with a spider-net"
 mimetype = "image/svg+xml"
 artist = "Nicklas Larsson"
 date = "14.7.2005"
 organization = "The GNU Project"
 keywords = "GNUnet AND logo"
 contributor = "Christian Muellner"

Metadata specification only works for files in the top-level
directory, all other files will only be listed as part of the
top-level directories and be given metadata using libextractor.
.PP

\fB\-c \fIFILENAME\fR, \fB\-\-config=FILENAME\fR
Use alternate config file (if this option is not specified, the
default is ~/.gnunet/gnunet.conf).

.TP
\fB\-d\fR, \fB\-\-debug\fR
do not detach from the console (for debugging); log messages are written to stderr.

.TP
\fB\-D\fR, \fB\-\-disable\-direct\fR 
Disable direct indexing information that would otherwise refer to
files inside of directories directly.  Without \-D, contents can be
found directly using keywords extracted with libextractor.  Use \-D if
you index directories with many similar files that are adequately
described using keywords for the directory and for which individual
references would unduely pollte the global keyword search space.  Also
use \-D to disable libextractor for individual file publications.
This way you can ensure that a file will only be referenced using the
keywords that you are specifying explicitly.

.TP
\fB\-h\fR, \fB\-\-help\fR
Print a brief help page with all the options.

.TP
\fB\-H \fIHOSTNAME\fR, \fB\-\-host=\fIHOSTNAME\fR
on which host is gnunetd running (default: localhost).  You can also
specify a port using the syntax HOSTNAME:PORT.  The default port is
2087.

.TP
\fB\-L \fILOGLEVEL\fR, \fB\-\-loglevel=\fILOGLEVEL\fR
Change the loglevel.  Possible values for LOGLEVEL are NOTHING, FATAL,
ERROR, WARNING, INFO, STATUS and DEBUG.  Note that options in the 
configuration file take precedence over this option (the argument 
will be ignored in that case).

.TP
\fB\-p \fIPRIORITY\fR, \fB\-\-prio=\fIPRIORITY\fR
Executive summary: You probably don't need it.

Set the priority of the inserted content (default: 65535).  If the
local database is full, GNUnet will discard the content with the
lowest ranking.  Note that ranks change over time depending on
popularity.  The default should be high enough to preserve the locally
inserted content in favor of content that migrates from other peers.

.TP
\fB\-v\fR, \fB\-\-version\fR
Print the version number.

.TP
\fB\-V\fR, \fB\-\-verbose\fR
Be verbose.  Using this option causes gnunet\-auto\-share to print 
progress information and the file identification that can be used to
download the file from GNUnet.


.SH EXAMPLES
.PP
Use the following command to have gnunet\-auto\-share run in the
background and share the "/home/share/" directory:

 $ gnunet\-auto\-share /home/share/ 

Use the following command to share the "/home/share/" directory
and see the URIs of uploaded files.  You can abort the daemon 
with CTRL-C:

 $ gnunet\-auto\-share -d -V /home/share/ 


.SH FILES
.TP
~/.gnunet/gnunet.conf
GNUnet configuration file
.SH "REPORTING BUGS"
Report bugs by using mantis <https://gnunet.org/mantis/> or by sending electronic mail to <gnunet\-developers@gnu.org>
.SH "SEE ALSO"
\fBgnunet\-gtk\fP(1), \fBgnunet\-insert\fP(1), \fBgnunet\-search\fP(1), \fBgnunet\-download\fP(1), \fBgnunet.conf\fP(5), \fBgnunetd\fP(1), \fBextract\fP(1)
