.TH GNUNET.CONF "5" "11 Nov 2006" "GNUnet"
.SH NAME
gnunet.conf \- GNUnet client configuration file
.SH SYNOPSIS
~/.gnunet/gnunet.conf
.SH DESCRIPTION
.PP
GNUnet uses two configuation files, one for user interfaces (gnunet.conf) and one for the server (gnunetd) and associated administrative tools.  This man page describes the configuration file for the clients.
.PP
~/.gnunet/gnunet.conf is the default location for the configuration file used by the gnunet clients (such as gnunet\-gtk, gnunet\-insert, gnunet\-search, etc.).   Use gnunet\-setup to create the configuration.  The defaults should work fine for most users.
.TP
The configuration file is used to allow users to customize GNUnet according to their needs.  The user configuration allows the specification of personal options, such as the nickname in the chat. 
.TP
The basic structure of the configuration file is the following.  The file is split into sections.  Every section begins with [SECTIONNAME] and contains a number of options of the form OPTION=VALUE.  Empty lines and lines beginning with a # are treated as comments.  Almost all options are optional and the tools resort to reasonable defaults if they are not present.
.SH FILES
.TP
~/.gnunet/gnunet.conf
GNUnet client (per local user) configuration file
.SH "REPORTING BUGS"
Report bugs by using mantis <https://gnunet.org/mantis/> or by sending electronic mail to <gnunet-developers@gnu.org>
.SH "SEE ALSO"
\fBgnunet\-setup\fP(1), \fBgnunetd.conf\fP(5), \fBgnunet\-update\fP(1)
