/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget *create_assi_step1 (void);
GtkWidget *create_assi_step2 (void);
GtkWidget *create_assi_step3 (void);
GtkWidget *create_assi_step5 (void);
GtkWidget *create_msgSave (void);
GtkWidget *create_msgSaveFailed (void);
GtkWidget *create_assi_step4 (void);
