/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "wizard_callbacks.h"
#include "wizard_interface.h"
#include "wizard_support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget *
create_assi_step1 (void)
{
  GtkWidget *assi_step1;
  GtkWidget *vbox2;
  GtkWidget *scoll_welcome;
  GtkWidget *textview11;
  GtkWidget *hseparator2;
  GtkWidget *hbuttonbox1;
  GtkWidget *step1_next;
  GtkWidget *alignment31;
  GtkWidget *hbox54;
  GtkWidget *image64;
  GtkWidget *label85;
  GtkWidget *abort;
  GtkWidget *alignment32;
  GtkWidget *hbox55;
  GtkWidget *image65;
  GtkWidget *label86;

  assi_step1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (assi_step1, 450, 350);
  gtk_window_set_title (GTK_WINDOW (assi_step1),
			_("GNUnet configuration assistant"));
  gtk_window_set_position (GTK_WINDOW (assi_step1), GTK_WIN_POS_CENTER);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (assi_step1), vbox2);

  scoll_welcome = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scoll_welcome);
  gtk_box_pack_start (GTK_BOX (vbox2), scoll_welcome, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scoll_welcome),
				  GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  textview11 = gtk_text_view_new ();
  gtk_widget_show (textview11);
  gtk_container_add (GTK_CONTAINER (scoll_welcome), textview11);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (textview11), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (textview11), GTK_WRAP_WORD);
  gtk_text_view_set_cursor_visible (GTK_TEXT_VIEW (textview11), FALSE);
  gtk_text_view_set_indent (GTK_TEXT_VIEW (textview11), 2);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer
			    (GTK_TEXT_VIEW (textview11)),
			    _
			    ("Welcome to GNUnet!\n\nThis assistant will ask you a few basic questions in order to configure GNUnet.\n\nPlease visit our homepage at\n\thttp://gnunet.org\nand join our community at\n\thttps://gnunet.org/drupal/\n\nHave a lot of fun,\n\nthe GNUnet team"),
			    -1);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (vbox2), hseparator2, FALSE, TRUE, 0);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox2), hbuttonbox1, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_END);

  step1_next = gtk_button_new ();
  gtk_widget_show (step1_next);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), step1_next);
  GTK_WIDGET_SET_FLAGS (step1_next, GTK_CAN_DEFAULT);

  alignment31 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment31);
  gtk_container_add (GTK_CONTAINER (step1_next), alignment31);

  hbox54 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox54);
  gtk_container_add (GTK_CONTAINER (alignment31), hbox54);

  image64 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image64);
  gtk_box_pack_start (GTK_BOX (hbox54), image64, FALSE, FALSE, 0);

  label85 = gtk_label_new_with_mnemonic (_("Next"));
  gtk_widget_show (label85);
  gtk_box_pack_start (GTK_BOX (hbox54), label85, FALSE, FALSE, 0);

  abort = gtk_button_new ();
  gtk_widget_show (abort);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), abort);
  GTK_WIDGET_SET_FLAGS (abort, GTK_CAN_DEFAULT);

  alignment32 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment32);
  gtk_container_add (GTK_CONTAINER (abort), alignment32);

  hbox55 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox55);
  gtk_container_add (GTK_CONTAINER (alignment32), hbox55);

  image65 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image65);
  gtk_box_pack_start (GTK_BOX (hbox55), image65, FALSE, FALSE, 0);

  label86 = gtk_label_new_with_mnemonic (_("Cancel"));
  gtk_widget_show (label86);
  gtk_box_pack_start (GTK_BOX (hbox55), label86, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) assi_step1, "destroy",
		    G_CALLBACK (on_assi_destroy), NULL);
  g_signal_connect ((gpointer) step1_next, "clicked",
		    G_CALLBACK (on_step1_next_clicked), NULL);
  g_signal_connect ((gpointer) abort, "clicked",
		    G_CALLBACK (on_abort_clicked), NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (assi_step1, assi_step1, "assi_step1");
  GLADE_HOOKUP_OBJECT (assi_step1, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (assi_step1, scoll_welcome, "scoll_welcome");
  GLADE_HOOKUP_OBJECT (assi_step1, textview11, "textview11");
  GLADE_HOOKUP_OBJECT (assi_step1, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (assi_step1, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (assi_step1, step1_next, "step1_next");
  GLADE_HOOKUP_OBJECT (assi_step1, alignment31, "alignment31");
  GLADE_HOOKUP_OBJECT (assi_step1, hbox54, "hbox54");
  GLADE_HOOKUP_OBJECT (assi_step1, image64, "image64");
  GLADE_HOOKUP_OBJECT (assi_step1, label85, "label85");
  GLADE_HOOKUP_OBJECT (assi_step1, abort, "abort");
  GLADE_HOOKUP_OBJECT (assi_step1, alignment32, "alignment32");
  GLADE_HOOKUP_OBJECT (assi_step1, hbox55, "hbox55");
  GLADE_HOOKUP_OBJECT (assi_step1, image65, "image65");
  GLADE_HOOKUP_OBJECT (assi_step1, label86, "label86");

  return assi_step1;
}

GtkWidget *
create_assi_step2 (void)
{
  GtkWidget *assi_step2;
  GtkWidget *vbox3;
  GtkWidget *frame1;
  GtkWidget *vbox4;
  GtkWidget *scrolledwindow5;
  GtkWidget *textview8;
  GtkWidget *hseparator3;
  GtkWidget *vbox5;
  GtkWidget *vbox6;
  GtkWidget *table1;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *entIP;
  GtkWidget *chkFW;
  GtkWidget *cmbNIC;
  GtkWidget *labelLimit;
  GtkWidget *hbuttonbox2;
  GtkWidget *step2_back;
  GtkWidget *alignment33;
  GtkWidget *hbox56;
  GtkWidget *image66;
  GtkWidget *label87;
  GtkWidget *step2_next;
  GtkWidget *alignment41;
  GtkWidget *hbox64;
  GtkWidget *image74;
  GtkWidget *label95;
  GtkWidget *step2_abort;
  GtkWidget *alignment42;
  GtkWidget *hbox68;
  GtkWidget *image78;
  GtkWidget *label99;

  assi_step2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (assi_step2, 450, 350);
  gtk_window_set_title (GTK_WINDOW (assi_step2),
			_("GNUnet configuration assistant"));
  gtk_window_set_position (GTK_WINDOW (assi_step2), GTK_WIN_POS_CENTER);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (assi_step2), vbox3);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox3), frame1, TRUE, TRUE, 0);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (frame1), vbox4);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_box_pack_start (GTK_BOX (vbox4), scrolledwindow5, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow5),
				  GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  textview8 = gtk_text_view_new ();
  gtk_widget_show (textview8);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), textview8);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (textview8), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (textview8), GTK_WRAP_WORD);
  gtk_text_view_set_cursor_visible (GTK_TEXT_VIEW (textview8), FALSE);
  gtk_text_view_set_left_margin (GTK_TEXT_VIEW (textview8), 2);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer
			    (GTK_TEXT_VIEW (textview8)),
			    _
			    ("Enter information about your network connection here.\n\nThe \"Network interface\" is the device that connects your computer to the internet. This is usually a modem, an ISDN card or a network card in case you are using DSL.\n\nIf your provider always assigns the same IP-Address to you (a \"static\" IP-Address), enter it into the \"IP-Address\" field. If your IP-Address changes every now and then (\"dynamic\" IP-Address) but there's a hostname that always points to your actual IP-Address (\"Dynamic DNS\"), you can also enter it here.\nIf in doubt, leave the field empty. GNUnet will then try to determine your IP-Address.\n\nIf you are connected to the internet through another computer doing SNAT, a router or a \"hardware firewall\" and other computers on the internet cannot connect to this computer, check the last option on this page. Leave it unchecked on direct connections through modems, ISDN cards and DNAT (also known as \"port forwarding\")."),
			    -1);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_box_pack_start (GTK_BOX (vbox4), hseparator3, FALSE, FALSE, 0);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (vbox4), vbox5, TRUE, TRUE, 0);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_box_pack_start (GTK_BOX (vbox5), vbox6, TRUE, TRUE, 0);

  table1 = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox6), table1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 5);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 5);

  label23 = gtk_label_new (_("Network interface:"));
  gtk_widget_show (label23);
  gtk_table_attach (GTK_TABLE (table1), label23, 0, 1, 0, 1,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);

  label24 = gtk_label_new (_("IP-Address/Hostname:"));
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (table1), label24, 0, 1, 1, 2,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);

  entIP = gtk_entry_new ();
  gtk_widget_show (entIP);
  gtk_table_attach (GTK_TABLE (table1), entIP, 1, 2, 1, 2,
		    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);

  chkFW =
    gtk_check_button_new_with_mnemonic (_
					("Computer cannot receive inbound connections (SNAT/Firewall)"));
  gtk_widget_show (chkFW);
  gtk_table_attach (GTK_TABLE (table1), chkFW, 0, 2, 2, 3,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);

  cmbNIC = gtk_combo_box_entry_new_text ();
  gtk_widget_show (cmbNIC);
  gtk_table_attach (GTK_TABLE (table1), cmbNIC, 1, 2, 0, 1,
		    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL),
		    (GtkAttachOptions) (GTK_FILL), 0, 0);

  labelLimit = gtk_label_new (_("Network connection"));
  gtk_widget_show (labelLimit);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), labelLimit);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (vbox3), hbuttonbox2, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_END);

  step2_back = gtk_button_new ();
  gtk_widget_show (step2_back);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), step2_back);
  GTK_WIDGET_SET_FLAGS (step2_back, GTK_CAN_DEFAULT);

  alignment33 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment33);
  gtk_container_add (GTK_CONTAINER (step2_back), alignment33);

  hbox56 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox56);
  gtk_container_add (GTK_CONTAINER (alignment33), hbox56);

  image66 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image66);
  gtk_box_pack_start (GTK_BOX (hbox56), image66, FALSE, FALSE, 0);

  label87 = gtk_label_new_with_mnemonic (_("Back"));
  gtk_widget_show (label87);
  gtk_box_pack_start (GTK_BOX (hbox56), label87, FALSE, FALSE, 0);

  step2_next = gtk_button_new ();
  gtk_widget_show (step2_next);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), step2_next);
  GTK_WIDGET_SET_FLAGS (step2_next, GTK_CAN_DEFAULT);

  alignment41 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment41);
  gtk_container_add (GTK_CONTAINER (step2_next), alignment41);

  hbox64 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox64);
  gtk_container_add (GTK_CONTAINER (alignment41), hbox64);

  image74 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image74);
  gtk_box_pack_start (GTK_BOX (hbox64), image74, FALSE, FALSE, 0);

  label95 = gtk_label_new_with_mnemonic (_("Next"));
  gtk_widget_show (label95);
  gtk_box_pack_start (GTK_BOX (hbox64), label95, FALSE, FALSE, 0);

  step2_abort = gtk_button_new ();
  gtk_widget_show (step2_abort);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), step2_abort);
  GTK_WIDGET_SET_FLAGS (step2_abort, GTK_CAN_DEFAULT);

  alignment42 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment42);
  gtk_container_add (GTK_CONTAINER (step2_abort), alignment42);

  hbox68 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox68);
  gtk_container_add (GTK_CONTAINER (alignment42), hbox68);

  image78 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image78);
  gtk_box_pack_start (GTK_BOX (hbox68), image78, FALSE, FALSE, 0);

  label99 = gtk_label_new_with_mnemonic (_("Cancel"));
  gtk_widget_show (label99);
  gtk_box_pack_start (GTK_BOX (hbox68), label99, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) assi_step2, "destroy",
		    G_CALLBACK (on_assi_destroy), NULL);
  g_signal_connect ((gpointer) entIP, "changed",
		    G_CALLBACK (on_entIP_changed), NULL);
  g_signal_connect ((gpointer) chkFW, "toggled",
		    G_CALLBACK (on_chkFW_toggled), NULL);
  g_signal_connect ((gpointer) cmbNIC, "changed",
		    G_CALLBACK (on_cmbNIC_changed), NULL);
  g_signal_connect ((gpointer) step2_back, "clicked",
		    G_CALLBACK (on_step2_back_clicked), NULL);
  g_signal_connect ((gpointer) step2_next, "clicked",
		    G_CALLBACK (on_step2_next_clicked), NULL);
  g_signal_connect ((gpointer) step2_abort, "clicked",
		    G_CALLBACK (on_abort_clicked), NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (assi_step2, assi_step2, "assi_step2");
  GLADE_HOOKUP_OBJECT (assi_step2, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (assi_step2, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (assi_step2, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (assi_step2, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (assi_step2, textview8, "textview8");
  GLADE_HOOKUP_OBJECT (assi_step2, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (assi_step2, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (assi_step2, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (assi_step2, table1, "table1");
  GLADE_HOOKUP_OBJECT (assi_step2, label23, "label23");
  GLADE_HOOKUP_OBJECT (assi_step2, label24, "label24");
  GLADE_HOOKUP_OBJECT (assi_step2, entIP, "entIP");
  GLADE_HOOKUP_OBJECT (assi_step2, chkFW, "chkFW");
  GLADE_HOOKUP_OBJECT (assi_step2, cmbNIC, "cmbNIC");
  GLADE_HOOKUP_OBJECT (assi_step2, labelLimit, "labelLimit");
  GLADE_HOOKUP_OBJECT (assi_step2, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (assi_step2, step2_back, "step2_back");
  GLADE_HOOKUP_OBJECT (assi_step2, alignment33, "alignment33");
  GLADE_HOOKUP_OBJECT (assi_step2, hbox56, "hbox56");
  GLADE_HOOKUP_OBJECT (assi_step2, image66, "image66");
  GLADE_HOOKUP_OBJECT (assi_step2, label87, "label87");
  GLADE_HOOKUP_OBJECT (assi_step2, step2_next, "step2_next");
  GLADE_HOOKUP_OBJECT (assi_step2, alignment41, "alignment41");
  GLADE_HOOKUP_OBJECT (assi_step2, hbox64, "hbox64");
  GLADE_HOOKUP_OBJECT (assi_step2, image74, "image74");
  GLADE_HOOKUP_OBJECT (assi_step2, label95, "label95");
  GLADE_HOOKUP_OBJECT (assi_step2, step2_abort, "step2_abort");
  GLADE_HOOKUP_OBJECT (assi_step2, alignment42, "alignment42");
  GLADE_HOOKUP_OBJECT (assi_step2, hbox68, "hbox68");
  GLADE_HOOKUP_OBJECT (assi_step2, image78, "image78");
  GLADE_HOOKUP_OBJECT (assi_step2, label99, "label99");

  return assi_step2;
}

GtkWidget *
create_assi_step3 (void)
{
  GtkWidget *assi_step3;
  GtkWidget *vbox7;
  GtkWidget *frame3;
  GtkWidget *vbox8;
  GtkWidget *scrolledwindow6;
  GtkWidget *textview9;
  GtkWidget *hseparator4;
  GtkWidget *vbox9;
  GtkWidget *vbox10;
  GtkWidget *frame4;
  GtkWidget *hbox24;
  GtkWidget *table2;
  GtkWidget *label32;
  GtkWidget *entUp;
  GtkWidget *label33;
  GtkWidget *entDown;
  GtkWidget *label31;
  GtkWidget *frame5;
  GtkWidget *vbox11;
  GtkWidget *radGNUnet;
  GSList *radGNUnet_group = NULL;
  GtkWidget *radShare;
  GtkWidget *label34;
  GtkWidget *frame6;
  GtkWidget *hbox25;
  GtkWidget *label36;
  GtkWidget *entCPU;
  GtkWidget *label35;
  GtkWidget *label27;
  GtkWidget *hbuttonbox4;
  GtkWidget *step3_back;
  GtkWidget *alignment34;
  GtkWidget *hbox57;
  GtkWidget *image67;
  GtkWidget *label88;
  GtkWidget *step3_next;
  GtkWidget *alignment35;
  GtkWidget *hbox58;
  GtkWidget *image68;
  GtkWidget *label89;
  GtkWidget *step3_abort;
  GtkWidget *alignment36;
  GtkWidget *hbox59;
  GtkWidget *image69;
  GtkWidget *label90;

  assi_step3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (assi_step3, 450, 350);
  gtk_window_set_title (GTK_WINDOW (assi_step3),
			_("GNUnet configuration assistant"));
  gtk_window_set_position (GTK_WINDOW (assi_step3), GTK_WIN_POS_CENTER);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (assi_step3), vbox7);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (vbox7), frame3, TRUE, TRUE, 0);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (frame3), vbox8);

  scrolledwindow6 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow6);
  gtk_box_pack_start (GTK_BOX (vbox8), scrolledwindow6, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow6),
				  GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  textview9 = gtk_text_view_new ();
  gtk_widget_show (textview9);
  gtk_container_add (GTK_CONTAINER (scrolledwindow6), textview9);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (textview9), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (textview9), GTK_WRAP_WORD);
  gtk_text_view_set_cursor_visible (GTK_TEXT_VIEW (textview9), FALSE);
  gtk_text_view_set_left_margin (GTK_TEXT_VIEW (textview9), 2);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer
			    (GTK_TEXT_VIEW (textview9)),
			    _
			    ("You can limit GNUnet's ressource usage here.\n\n\"Bandwidth limitation\" is how much data may be sent per second. If you have a flatrate you can set it to the maximum speed of your internet connection.\n\nThe \"Max. CPU usage\" is the percentage of processor time GNUnet is allowed to use."),
			    -1);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_show (hseparator4);
  gtk_box_pack_start (GTK_BOX (vbox8), hseparator4, FALSE, TRUE, 0);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox9);
  gtk_box_pack_start (GTK_BOX (vbox8), vbox9, TRUE, TRUE, 0);

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox10);
  gtk_box_pack_start (GTK_BOX (vbox9), vbox10, TRUE, TRUE, 0);

  frame4 = gtk_frame_new (NULL);
  gtk_widget_show (frame4);
  gtk_box_pack_start (GTK_BOX (vbox10), frame4, TRUE, TRUE, 0);

  hbox24 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (frame4), hbox24);

  table2 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (hbox24), table2, TRUE, TRUE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table2), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 5);

  label32 = gtk_label_new (_("Upstream (Bytes/s):"));
  gtk_widget_show (label32);
  gtk_table_attach (GTK_TABLE (table2), label32, 0, 1, 0, 1,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label32), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label32), 5, 0);

  entUp = gtk_entry_new ();
  gtk_widget_show (entUp);
  gtk_table_attach (GTK_TABLE (table2), entUp, 1, 2, 0, 1,
		    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);

  label33 = gtk_label_new (_("Downstream (Bytes/s):"));
  gtk_widget_show (label33);
  gtk_table_attach (GTK_TABLE (table2), label33, 0, 1, 1, 2,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label33), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label33), 5, 0);

  entDown = gtk_entry_new ();
  gtk_widget_show (entDown);
  gtk_table_attach (GTK_TABLE (table2), entDown, 1, 2, 1, 2,
		    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);

  label31 = gtk_label_new (_("Bandwidth limitation"));
  gtk_widget_show (label31);
  gtk_frame_set_label_widget (GTK_FRAME (frame4), label31);

  frame5 = gtk_frame_new (NULL);
  gtk_widget_show (frame5);
  gtk_box_pack_start (GTK_BOX (vbox10), frame5, TRUE, TRUE, 0);

  vbox11 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox11);
  gtk_container_add (GTK_CONTAINER (frame5), vbox11);

  radGNUnet =
    gtk_radio_button_new_with_mnemonic (NULL,
					_
					("Use denoted bandwidth for GNUnet"));
  gtk_widget_show (radGNUnet);
  gtk_box_pack_start (GTK_BOX (vbox11), radGNUnet, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radGNUnet), radGNUnet_group);
  radGNUnet_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radGNUnet));

  radShare =
    gtk_radio_button_new_with_mnemonic (NULL,
					_
					("Share denoted bandwidth with other applications"));
  gtk_widget_show (radShare);
  gtk_box_pack_start (GTK_BOX (vbox11), radShare, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radShare), radGNUnet_group);
  radGNUnet_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radShare));

  label34 = gtk_label_new (_("Bandwidth sharing"));
  gtk_widget_show (label34);
  gtk_frame_set_label_widget (GTK_FRAME (frame5), label34);

  frame6 = gtk_frame_new (NULL);
  gtk_widget_show (frame6);
  gtk_box_pack_start (GTK_BOX (vbox10), frame6, TRUE, TRUE, 0);

  hbox25 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (frame6), hbox25);

  label36 = gtk_label_new (_("Max. CPU usage (%):"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox25), label36, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label36), 5, 0);

  entCPU = gtk_entry_new ();
  gtk_widget_show (entCPU);
  gtk_box_pack_start (GTK_BOX (hbox25), entCPU, TRUE, TRUE, 0);

  label35 = gtk_label_new (_("CPU usage"));
  gtk_widget_show (label35);
  gtk_frame_set_label_widget (GTK_FRAME (frame6), label35);

  label27 = gtk_label_new (_("Load limitation"));
  gtk_widget_show (label27);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label27);

  hbuttonbox4 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox4);
  gtk_box_pack_start (GTK_BOX (vbox7), hbuttonbox4, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox4), GTK_BUTTONBOX_END);

  step3_back = gtk_button_new ();
  gtk_widget_show (step3_back);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), step3_back);
  GTK_WIDGET_SET_FLAGS (step3_back, GTK_CAN_DEFAULT);

  alignment34 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment34);
  gtk_container_add (GTK_CONTAINER (step3_back), alignment34);

  hbox57 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox57);
  gtk_container_add (GTK_CONTAINER (alignment34), hbox57);

  image67 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image67);
  gtk_box_pack_start (GTK_BOX (hbox57), image67, FALSE, FALSE, 0);

  label88 = gtk_label_new_with_mnemonic (_("Back"));
  gtk_widget_show (label88);
  gtk_box_pack_start (GTK_BOX (hbox57), label88, FALSE, FALSE, 0);

  step3_next = gtk_button_new ();
  gtk_widget_show (step3_next);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), step3_next);
  GTK_WIDGET_SET_FLAGS (step3_next, GTK_CAN_DEFAULT);

  alignment35 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment35);
  gtk_container_add (GTK_CONTAINER (step3_next), alignment35);

  hbox58 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox58);
  gtk_container_add (GTK_CONTAINER (alignment35), hbox58);

  image68 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image68);
  gtk_box_pack_start (GTK_BOX (hbox58), image68, FALSE, FALSE, 0);

  label89 = gtk_label_new_with_mnemonic (_("Next"));
  gtk_widget_show (label89);
  gtk_box_pack_start (GTK_BOX (hbox58), label89, FALSE, FALSE, 0);

  step3_abort = gtk_button_new ();
  gtk_widget_show (step3_abort);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), step3_abort);
  GTK_WIDGET_SET_FLAGS (step3_abort, GTK_CAN_DEFAULT);

  alignment36 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment36);
  gtk_container_add (GTK_CONTAINER (step3_abort), alignment36);

  hbox59 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox59);
  gtk_container_add (GTK_CONTAINER (alignment36), hbox59);

  image69 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image69);
  gtk_box_pack_start (GTK_BOX (hbox59), image69, FALSE, FALSE, 0);

  label90 = gtk_label_new_with_mnemonic (_("Cancel"));
  gtk_widget_show (label90);
  gtk_box_pack_start (GTK_BOX (hbox59), label90, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) assi_step3, "destroy",
		    G_CALLBACK (on_assi_destroy), NULL);
  g_signal_connect ((gpointer) entUp, "changed",
		    G_CALLBACK (on_entUp_changed), NULL);
  g_signal_connect ((gpointer) entDown, "changed",
		    G_CALLBACK (on_entDown_changed), NULL);
  g_signal_connect ((gpointer) radGNUnet, "toggled",
		    G_CALLBACK (on_radGNUnet_toggled), NULL);
  g_signal_connect ((gpointer) radShare, "toggled",
		    G_CALLBACK (on_radShare_toggled), NULL);
  g_signal_connect ((gpointer) entCPU, "changed",
		    G_CALLBACK (on_entCPU_changed), NULL);
  g_signal_connect ((gpointer) step3_back, "clicked",
		    G_CALLBACK (on_step3_back_clicked), NULL);
  g_signal_connect ((gpointer) step3_next, "clicked",
		    G_CALLBACK (on_step3_next_clicked), NULL);
  g_signal_connect ((gpointer) step3_abort, "clicked",
		    G_CALLBACK (on_abort_clicked), NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (assi_step3, assi_step3, "assi_step3");
  GLADE_HOOKUP_OBJECT (assi_step3, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (assi_step3, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (assi_step3, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (assi_step3, scrolledwindow6, "scrolledwindow6");
  GLADE_HOOKUP_OBJECT (assi_step3, textview9, "textview9");
  GLADE_HOOKUP_OBJECT (assi_step3, hseparator4, "hseparator4");
  GLADE_HOOKUP_OBJECT (assi_step3, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (assi_step3, vbox10, "vbox10");
  GLADE_HOOKUP_OBJECT (assi_step3, frame4, "frame4");
  GLADE_HOOKUP_OBJECT (assi_step3, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (assi_step3, table2, "table2");
  GLADE_HOOKUP_OBJECT (assi_step3, label32, "label32");
  GLADE_HOOKUP_OBJECT (assi_step3, entUp, "entUp");
  GLADE_HOOKUP_OBJECT (assi_step3, label33, "label33");
  GLADE_HOOKUP_OBJECT (assi_step3, entDown, "entDown");
  GLADE_HOOKUP_OBJECT (assi_step3, label31, "label31");
  GLADE_HOOKUP_OBJECT (assi_step3, frame5, "frame5");
  GLADE_HOOKUP_OBJECT (assi_step3, vbox11, "vbox11");
  GLADE_HOOKUP_OBJECT (assi_step3, radGNUnet, "radGNUnet");
  GLADE_HOOKUP_OBJECT (assi_step3, radShare, "radShare");
  GLADE_HOOKUP_OBJECT (assi_step3, label34, "label34");
  GLADE_HOOKUP_OBJECT (assi_step3, frame6, "frame6");
  GLADE_HOOKUP_OBJECT (assi_step3, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (assi_step3, label36, "label36");
  GLADE_HOOKUP_OBJECT (assi_step3, entCPU, "entCPU");
  GLADE_HOOKUP_OBJECT (assi_step3, label35, "label35");
  GLADE_HOOKUP_OBJECT (assi_step3, label27, "label27");
  GLADE_HOOKUP_OBJECT (assi_step3, hbuttonbox4, "hbuttonbox4");
  GLADE_HOOKUP_OBJECT (assi_step3, step3_back, "step3_back");
  GLADE_HOOKUP_OBJECT (assi_step3, alignment34, "alignment34");
  GLADE_HOOKUP_OBJECT (assi_step3, hbox57, "hbox57");
  GLADE_HOOKUP_OBJECT (assi_step3, image67, "image67");
  GLADE_HOOKUP_OBJECT (assi_step3, label88, "label88");
  GLADE_HOOKUP_OBJECT (assi_step3, step3_next, "step3_next");
  GLADE_HOOKUP_OBJECT (assi_step3, alignment35, "alignment35");
  GLADE_HOOKUP_OBJECT (assi_step3, hbox58, "hbox58");
  GLADE_HOOKUP_OBJECT (assi_step3, image68, "image68");
  GLADE_HOOKUP_OBJECT (assi_step3, label89, "label89");
  GLADE_HOOKUP_OBJECT (assi_step3, step3_abort, "step3_abort");
  GLADE_HOOKUP_OBJECT (assi_step3, alignment36, "alignment36");
  GLADE_HOOKUP_OBJECT (assi_step3, hbox59, "hbox59");
  GLADE_HOOKUP_OBJECT (assi_step3, image69, "image69");
  GLADE_HOOKUP_OBJECT (assi_step3, label90, "label90");

  return assi_step3;
}

GtkWidget *
create_assi_step5 (void)
{
  GtkWidget *assi_step5;
  GtkWidget *vbox12;
  GtkWidget *frame7;
  GtkWidget *vbox13;
  GtkWidget *scrolledwindow7;
  GtkWidget *textview10;
  GtkWidget *hseparator5;
  GtkWidget *vbox14;
  GtkWidget *vbox15;
  GtkWidget *chkMigr;
  GtkWidget *hbox53;
  GtkWidget *label84;
  GtkWidget *entQuota;
  GtkWidget *chkStart;
  GtkWidget *chkEnh;
  GtkWidget *label43;
  GtkWidget *hbuttonbox5;
  GtkWidget *step5_back;
  GtkWidget *alignment37;
  GtkWidget *hbox60;
  GtkWidget *image70;
  GtkWidget *label91;
  GtkWidget *step5_next;
  GtkWidget *alignment40;
  GtkWidget *hbox63;
  GtkWidget *image73;
  GtkWidget *label94;
  GtkWidget *step5_cancel;
  GtkWidget *alignment39;
  GtkWidget *hbox62;
  GtkWidget *image72;
  GtkWidget *label93;

  assi_step5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (assi_step5, 450, 350);
  gtk_window_set_title (GTK_WINDOW (assi_step5),
			_("GNUnet configuration assistant"));
  gtk_window_set_position (GTK_WINDOW (assi_step5), GTK_WIN_POS_CENTER);

  vbox12 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox12);
  gtk_container_add (GTK_CONTAINER (assi_step5), vbox12);

  frame7 = gtk_frame_new (NULL);
  gtk_widget_show (frame7);
  gtk_box_pack_start (GTK_BOX (vbox12), frame7, TRUE, TRUE, 0);

  vbox13 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox13);
  gtk_container_add (GTK_CONTAINER (frame7), vbox13);

  scrolledwindow7 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow7);
  gtk_box_pack_start (GTK_BOX (vbox13), scrolledwindow7, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow7),
				  GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  textview10 = gtk_text_view_new ();
  gtk_widget_show (textview10);
  gtk_container_add (GTK_CONTAINER (scrolledwindow7), textview10);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (textview10), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (textview10), GTK_WRAP_WORD);
  gtk_text_view_set_cursor_visible (GTK_TEXT_VIEW (textview10), FALSE);
  gtk_text_view_set_left_margin (GTK_TEXT_VIEW (textview10), 2);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer
			    (GTK_TEXT_VIEW (textview10)),
			    _
			    ("GNUnet is able to store data from other peers in your datastore. This is useful if an adversary has access to your inserted content and you need to deny that the content is yours. With \"content migration\" on, the content could have \"migrated\" over the internet to your node without your knowledge.\nIt also helps to spread popular content over different peers to enhance availability.\n\nThe GNUnet datastore contains all data that GNUnet generates (index data, inserted and migrated content). Its maximum size can be specified below.\n\nIf you are an experienced user, you may want to tweak your GNUnet installation using the enhanced configurator."),
			    -1);

  hseparator5 = gtk_hseparator_new ();
  gtk_widget_show (hseparator5);
  gtk_box_pack_start (GTK_BOX (vbox13), hseparator5, FALSE, FALSE, 0);

  vbox14 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox14);
  gtk_box_pack_start (GTK_BOX (vbox13), vbox14, TRUE, TRUE, 0);

  vbox15 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox15);
  gtk_box_pack_start (GTK_BOX (vbox14), vbox15, TRUE, TRUE, 0);

  chkMigr = gtk_check_button_new_with_mnemonic (_("Store migrated content"));
  gtk_widget_show (chkMigr);
  gtk_box_pack_start (GTK_BOX (vbox15), chkMigr, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (chkMigr), 4);

  hbox53 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox53);
  gtk_box_pack_start (GTK_BOX (vbox15), hbox53, TRUE, TRUE, 0);

  label84 = gtk_label_new (_("Maximum datastore size (MB):"));
  gtk_widget_show (label84);
  gtk_box_pack_start (GTK_BOX (hbox53), label84, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label84), 8, 0);

  entQuota = gtk_entry_new ();
  gtk_widget_show (entQuota);
  gtk_box_pack_start (GTK_BOX (hbox53), entQuota, TRUE, TRUE, 0);

  chkStart =
    gtk_check_button_new_with_mnemonic (_
					("Start the GNUnet background process on computer startup"));
  gtk_widget_show (chkStart);
  gtk_box_pack_start (GTK_BOX (vbox15), chkStart, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (chkStart), 4);
  gtk_widget_set_sensitive (chkStart, FALSE);

  chkEnh =
    gtk_check_button_new_with_mnemonic (_("Open the enhanced configurator"));
  gtk_widget_show (chkEnh);
  gtk_box_pack_start (GTK_BOX (vbox15), chkEnh, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (chkEnh), 5);

  label43 = gtk_label_new (_("Other settings"));
  gtk_widget_show (label43);
  gtk_frame_set_label_widget (GTK_FRAME (frame7), label43);

  hbuttonbox5 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox5);
  gtk_box_pack_start (GTK_BOX (vbox12), hbuttonbox5, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox5), GTK_BUTTONBOX_END);

  step5_back = gtk_button_new ();
  gtk_widget_show (step5_back);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), step5_back);
  GTK_WIDGET_SET_FLAGS (step5_back, GTK_CAN_DEFAULT);

  alignment37 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment37);
  gtk_container_add (GTK_CONTAINER (step5_back), alignment37);

  hbox60 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox60);
  gtk_container_add (GTK_CONTAINER (alignment37), hbox60);

  image70 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image70);
  gtk_box_pack_start (GTK_BOX (hbox60), image70, FALSE, FALSE, 0);

  label91 = gtk_label_new_with_mnemonic (_("Back"));
  gtk_widget_show (label91);
  gtk_box_pack_start (GTK_BOX (hbox60), label91, FALSE, FALSE, 0);

  step5_next = gtk_button_new ();
  gtk_widget_show (step5_next);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), step5_next);
  GTK_WIDGET_SET_FLAGS (step5_next, GTK_CAN_DEFAULT);

  alignment40 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment40);
  gtk_container_add (GTK_CONTAINER (step5_next), alignment40);

  hbox63 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox63);
  gtk_container_add (GTK_CONTAINER (alignment40), hbox63);

  image73 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image73);
  gtk_box_pack_start (GTK_BOX (hbox63), image73, FALSE, FALSE, 0);

  label94 = gtk_label_new_with_mnemonic (_("Finish"));
  gtk_widget_show (label94);
  gtk_box_pack_start (GTK_BOX (hbox63), label94, FALSE, FALSE, 0);

  step5_cancel = gtk_button_new ();
  gtk_widget_show (step5_cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), step5_cancel);
  GTK_WIDGET_SET_FLAGS (step5_cancel, GTK_CAN_DEFAULT);

  alignment39 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment39);
  gtk_container_add (GTK_CONTAINER (step5_cancel), alignment39);

  hbox62 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox62);
  gtk_container_add (GTK_CONTAINER (alignment39), hbox62);

  image72 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image72);
  gtk_box_pack_start (GTK_BOX (hbox62), image72, FALSE, FALSE, 0);

  label93 = gtk_label_new_with_mnemonic (_("Cancel"));
  gtk_widget_show (label93);
  gtk_box_pack_start (GTK_BOX (hbox62), label93, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) assi_step5, "destroy",
		    G_CALLBACK (on_assi_destroy), NULL);
  g_signal_connect ((gpointer) chkMigr, "toggled",
		    G_CALLBACK (on_chkMigr_toggled), NULL);
  g_signal_connect ((gpointer) entQuota, "changed",
		    G_CALLBACK (on_entQuota_changed), NULL);
  g_signal_connect ((gpointer) chkStart, "toggled",
		    G_CALLBACK (on_chkStart_toggled), NULL);
  g_signal_connect ((gpointer) chkEnh, "toggled",
		    G_CALLBACK (on_chkEnh_toggled), NULL);
  g_signal_connect ((gpointer) step5_back, "clicked",
		    G_CALLBACK (on_step5_back_clicked), NULL);
  g_signal_connect ((gpointer) step5_next, "clicked",
		    G_CALLBACK (on_finish_clicked), NULL);
  g_signal_connect ((gpointer) step5_cancel, "clicked",
		    G_CALLBACK (on_abort_clicked), NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (assi_step5, assi_step5, "assi_step5");
  GLADE_HOOKUP_OBJECT (assi_step5, vbox12, "vbox12");
  GLADE_HOOKUP_OBJECT (assi_step5, frame7, "frame7");
  GLADE_HOOKUP_OBJECT (assi_step5, vbox13, "vbox13");
  GLADE_HOOKUP_OBJECT (assi_step5, scrolledwindow7, "scrolledwindow7");
  GLADE_HOOKUP_OBJECT (assi_step5, textview10, "textview10");
  GLADE_HOOKUP_OBJECT (assi_step5, hseparator5, "hseparator5");
  GLADE_HOOKUP_OBJECT (assi_step5, vbox14, "vbox14");
  GLADE_HOOKUP_OBJECT (assi_step5, vbox15, "vbox15");
  GLADE_HOOKUP_OBJECT (assi_step5, chkMigr, "chkMigr");
  GLADE_HOOKUP_OBJECT (assi_step5, hbox53, "hbox53");
  GLADE_HOOKUP_OBJECT (assi_step5, label84, "label84");
  GLADE_HOOKUP_OBJECT (assi_step5, entQuota, "entQuota");
  GLADE_HOOKUP_OBJECT (assi_step5, chkStart, "chkStart");
  GLADE_HOOKUP_OBJECT (assi_step5, chkEnh, "chkEnh");
  GLADE_HOOKUP_OBJECT (assi_step5, label43, "label43");
  GLADE_HOOKUP_OBJECT (assi_step5, hbuttonbox5, "hbuttonbox5");
  GLADE_HOOKUP_OBJECT (assi_step5, step5_back, "step5_back");
  GLADE_HOOKUP_OBJECT (assi_step5, alignment37, "alignment37");
  GLADE_HOOKUP_OBJECT (assi_step5, hbox60, "hbox60");
  GLADE_HOOKUP_OBJECT (assi_step5, image70, "image70");
  GLADE_HOOKUP_OBJECT (assi_step5, label91, "label91");
  GLADE_HOOKUP_OBJECT (assi_step5, step5_next, "step5_next");
  GLADE_HOOKUP_OBJECT (assi_step5, alignment40, "alignment40");
  GLADE_HOOKUP_OBJECT (assi_step5, hbox63, "hbox63");
  GLADE_HOOKUP_OBJECT (assi_step5, image73, "image73");
  GLADE_HOOKUP_OBJECT (assi_step5, label94, "label94");
  GLADE_HOOKUP_OBJECT (assi_step5, step5_cancel, "step5_cancel");
  GLADE_HOOKUP_OBJECT (assi_step5, alignment39, "alignment39");
  GLADE_HOOKUP_OBJECT (assi_step5, hbox62, "hbox62");
  GLADE_HOOKUP_OBJECT (assi_step5, image72, "image72");
  GLADE_HOOKUP_OBJECT (assi_step5, label93, "label93");

  return assi_step5;
}

GtkWidget *
create_msgSave (void)
{
  GtkWidget *msgSave;
  GtkWidget *vbox16;
  GtkWidget *hbox65;
  GtkWidget *image75;
  GtkWidget *label96;
  GtkWidget *hseparator1;
  GtkWidget *hbuttonbox6;
  GtkWidget *saveYes;
  GtkWidget *saveNo;

  msgSave = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (msgSave), _("Question"));
  gtk_window_set_position (GTK_WINDOW (msgSave), GTK_WIN_POS_CENTER);

  vbox16 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox16);
  gtk_container_add (GTK_CONTAINER (msgSave), vbox16);

  hbox65 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox65);
  gtk_box_pack_start (GTK_BOX (vbox16), hbox65, TRUE, TRUE, 0);

  image75 =
    gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image75);
  gtk_box_pack_start (GTK_BOX (hbox65), image75, FALSE, TRUE, 15);
  gtk_misc_set_padding (GTK_MISC (image75), 0, 15);

  label96 = gtk_label_new (_("Do you want to save your settings?"));
  gtk_widget_show (label96);
  gtk_box_pack_start (GTK_BOX (hbox65), label96, FALSE, FALSE, 5);
  gtk_label_set_line_wrap (GTK_LABEL (label96), TRUE);
  gtk_misc_set_padding (GTK_MISC (label96), 0, 15);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox16), hseparator1, FALSE, TRUE, 0);

  hbuttonbox6 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox6);
  gtk_box_pack_start (GTK_BOX (vbox16), hbuttonbox6, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox6), GTK_BUTTONBOX_END);

  saveYes = gtk_button_new_with_mnemonic (_("Yes"));
  gtk_widget_show (saveYes);
  gtk_container_add (GTK_CONTAINER (hbuttonbox6), saveYes);
  GTK_WIDGET_SET_FLAGS (saveYes, GTK_CAN_DEFAULT);

  saveNo = gtk_button_new_with_mnemonic (_("No"));
  gtk_widget_show (saveNo);
  gtk_container_add (GTK_CONTAINER (hbuttonbox6), saveNo);
  GTK_WIDGET_SET_FLAGS (saveNo, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) saveYes, "clicked",
		    G_CALLBACK (on_saveYes_clicked), NULL);
  g_signal_connect ((gpointer) saveNo, "clicked",
		    G_CALLBACK (on_saveNo_clicked), NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (msgSave, msgSave, "msgSave");
  GLADE_HOOKUP_OBJECT (msgSave, vbox16, "vbox16");
  GLADE_HOOKUP_OBJECT (msgSave, hbox65, "hbox65");
  GLADE_HOOKUP_OBJECT (msgSave, image75, "image75");
  GLADE_HOOKUP_OBJECT (msgSave, label96, "label96");
  GLADE_HOOKUP_OBJECT (msgSave, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (msgSave, hbuttonbox6, "hbuttonbox6");
  GLADE_HOOKUP_OBJECT (msgSave, saveYes, "saveYes");
  GLADE_HOOKUP_OBJECT (msgSave, saveNo, "saveNo");

  return msgSave;
}

GtkWidget *
create_msgSaveFailed (void)
{
  GtkWidget *msgSaveFailed;
  GtkWidget *vbox17;
  GtkWidget *hbox67;
  GtkWidget *image77;
  GtkWidget *label98;
  GtkWidget *hseparator6;
  GtkWidget *hbuttonbox7;
  GtkWidget *button1;

  msgSaveFailed = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (msgSaveFailed), _("Error"));
  gtk_window_set_position (GTK_WINDOW (msgSaveFailed), GTK_WIN_POS_CENTER);

  vbox17 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox17);
  gtk_container_add (GTK_CONTAINER (msgSaveFailed), vbox17);

  hbox67 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox67);
  gtk_box_pack_start (GTK_BOX (vbox17), hbox67, TRUE, TRUE, 0);

  image77 =
    gtk_image_new_from_stock ("gtk-dialog-error", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image77);
  gtk_box_pack_start (GTK_BOX (hbox67), image77, FALSE, TRUE, 15);
  gtk_misc_set_padding (GTK_MISC (image77), 0, 15);

  label98 = gtk_label_new (_("Unable to save configuration!"));
  gtk_widget_show (label98);
  gtk_box_pack_start (GTK_BOX (hbox67), label98, FALSE, FALSE, 5);
  gtk_label_set_line_wrap (GTK_LABEL (label98), TRUE);
  gtk_misc_set_padding (GTK_MISC (label98), 0, 15);

  hseparator6 = gtk_hseparator_new ();
  gtk_widget_show (hseparator6);
  gtk_box_pack_start (GTK_BOX (vbox17), hseparator6, FALSE, TRUE, 0);

  hbuttonbox7 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox7);
  gtk_box_pack_start (GTK_BOX (vbox17), hbuttonbox7, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox7), GTK_BUTTONBOX_END);

  button1 = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (button1);
  gtk_container_add (GTK_CONTAINER (hbuttonbox7), button1);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) button1, "clicked",
		    G_CALLBACK (on_saveFailedOK_clicked), NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (msgSaveFailed, msgSaveFailed, "msgSaveFailed");
  GLADE_HOOKUP_OBJECT (msgSaveFailed, vbox17, "vbox17");
  GLADE_HOOKUP_OBJECT (msgSaveFailed, hbox67, "hbox67");
  GLADE_HOOKUP_OBJECT (msgSaveFailed, image77, "image77");
  GLADE_HOOKUP_OBJECT (msgSaveFailed, label98, "label98");
  GLADE_HOOKUP_OBJECT (msgSaveFailed, hseparator6, "hseparator6");
  GLADE_HOOKUP_OBJECT (msgSaveFailed, hbuttonbox7, "hbuttonbox7");
  GLADE_HOOKUP_OBJECT (msgSaveFailed, button1, "button1");

  return msgSaveFailed;
}

GtkWidget *
create_assi_step4 (void)
{
  GtkWidget *assi_step4;
  GtkWidget *vbox18;
  GtkWidget *frame8;
  GtkWidget *vbox19;
  GtkWidget *scrolledwindow8;
  GtkWidget *textview12;
  GtkWidget *hseparator7;
  GtkWidget *table3;
  GtkWidget *label110;
  GtkWidget *entUser;
  GtkWidget *entGroup;
  GtkWidget *label109;
  GtkWidget *label101;
  GtkWidget *hbuttonbox8;
  GtkWidget *step4_back;
  GtkWidget *alignment43;
  GtkWidget *hbox70;
  GtkWidget *image79;
  GtkWidget *label102;
  GtkWidget *step4_next;
  GtkWidget *alignment48;
  GtkWidget *hbox78;
  GtkWidget *image84;
  GtkWidget *label111;
  GtkWidget *step4_abort;
  GtkWidget *alignment45;
  GtkWidget *hbox72;
  GtkWidget *image81;
  GtkWidget *label104;

  assi_step4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (assi_step4, 450, 350);
  gtk_window_set_title (GTK_WINDOW (assi_step4),
			_("GNUnet configuration assistant"));
  gtk_window_set_position (GTK_WINDOW (assi_step4), GTK_WIN_POS_CENTER);

  vbox18 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox18);
  gtk_container_add (GTK_CONTAINER (assi_step4), vbox18);

  frame8 = gtk_frame_new (NULL);
  gtk_widget_show (frame8);
  gtk_box_pack_start (GTK_BOX (vbox18), frame8, TRUE, TRUE, 0);

  vbox19 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox19);
  gtk_container_add (GTK_CONTAINER (frame8), vbox19);

  scrolledwindow8 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow8);
  gtk_box_pack_start (GTK_BOX (vbox19), scrolledwindow8, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow8),
				  GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  textview12 = gtk_text_view_new ();
  gtk_widget_show (textview12);
  gtk_container_add (GTK_CONTAINER (scrolledwindow8), textview12);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (textview12), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (textview12), GTK_WRAP_WORD);
  gtk_text_view_set_cursor_visible (GTK_TEXT_VIEW (textview12), FALSE);
  gtk_text_view_set_left_margin (GTK_TEXT_VIEW (textview12), 2);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer
			    (GTK_TEXT_VIEW (textview12)),
			    _
			    ("Define the user and the group owning the GNUnet service here.\n\nFor security reasons, it is a good idea to let this setup create a new user account and a new group under which the GNUnet service is started at system startup.\n\nHowever, GNUnet may not be able to access files other than its own. This includes files you want to publish in GNUnet. You'll have to grant read permissions to the user specified below.\n\nLeave the fields empty to run GNUnet with system privileges."),
			    -1);

  hseparator7 = gtk_hseparator_new ();
  gtk_widget_show (hseparator7);
  gtk_box_pack_start (GTK_BOX (vbox19), hseparator7, FALSE, FALSE, 0);

  table3 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table3);
  gtk_box_pack_start (GTK_BOX (vbox19), table3, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table3), 5);
  gtk_table_set_row_spacings (GTK_TABLE (table3), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table3), 5);

  label110 = gtk_label_new (_("Group:"));
  gtk_widget_show (label110);
  gtk_table_attach (GTK_TABLE (table3), label110, 0, 1, 1, 2,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label110), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label110), 5, 0);

  entUser = gtk_entry_new ();
  gtk_widget_show (entUser);
  gtk_table_attach (GTK_TABLE (table3), entUser, 1, 2, 0, 1,
		    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);

  entGroup = gtk_entry_new ();
  gtk_widget_show (entGroup);
  gtk_table_attach (GTK_TABLE (table3), entGroup, 1, 2, 1, 2,
		    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);

  label109 = gtk_label_new (_("User account:"));
  gtk_widget_show (label109);
  gtk_table_attach (GTK_TABLE (table3), label109, 0, 1, 0, 1,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label109), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label109), 5, 0);

  label101 = gtk_label_new (_("Other settings"));
  gtk_widget_show (label101);
  gtk_frame_set_label_widget (GTK_FRAME (frame8), label101);

  hbuttonbox8 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox8);
  gtk_box_pack_start (GTK_BOX (vbox18), hbuttonbox8, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox8), GTK_BUTTONBOX_END);

  step4_back = gtk_button_new ();
  gtk_widget_show (step4_back);
  gtk_container_add (GTK_CONTAINER (hbuttonbox8), step4_back);
  GTK_WIDGET_SET_FLAGS (step4_back, GTK_CAN_DEFAULT);

  alignment43 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment43);
  gtk_container_add (GTK_CONTAINER (step4_back), alignment43);

  hbox70 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox70);
  gtk_container_add (GTK_CONTAINER (alignment43), hbox70);

  image79 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image79);
  gtk_box_pack_start (GTK_BOX (hbox70), image79, FALSE, FALSE, 0);

  label102 = gtk_label_new_with_mnemonic (_("Back"));
  gtk_widget_show (label102);
  gtk_box_pack_start (GTK_BOX (hbox70), label102, FALSE, FALSE, 0);

  step4_next = gtk_button_new ();
  gtk_widget_show (step4_next);
  gtk_container_add (GTK_CONTAINER (hbuttonbox8), step4_next);
  GTK_WIDGET_SET_FLAGS (step4_next, GTK_CAN_DEFAULT);

  alignment48 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment48);
  gtk_container_add (GTK_CONTAINER (step4_next), alignment48);

  hbox78 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox78);
  gtk_container_add (GTK_CONTAINER (alignment48), hbox78);

  image84 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image84);
  gtk_box_pack_start (GTK_BOX (hbox78), image84, FALSE, FALSE, 0);

  label111 = gtk_label_new_with_mnemonic (_("Next"));
  gtk_widget_show (label111);
  gtk_box_pack_start (GTK_BOX (hbox78), label111, FALSE, FALSE, 0);

  step4_abort = gtk_button_new ();
  gtk_widget_show (step4_abort);
  gtk_container_add (GTK_CONTAINER (hbuttonbox8), step4_abort);
  GTK_WIDGET_SET_FLAGS (step4_abort, GTK_CAN_DEFAULT);

  alignment45 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment45);
  gtk_container_add (GTK_CONTAINER (step4_abort), alignment45);

  hbox72 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox72);
  gtk_container_add (GTK_CONTAINER (alignment45), hbox72);

  image81 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image81);
  gtk_box_pack_start (GTK_BOX (hbox72), image81, FALSE, FALSE, 0);

  label104 = gtk_label_new_with_mnemonic (_("Cancel"));
  gtk_widget_show (label104);
  gtk_box_pack_start (GTK_BOX (hbox72), label104, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) assi_step4, "destroy",
		    G_CALLBACK (on_assi_destroy), NULL);
  g_signal_connect ((gpointer) entUser, "changed",
		    G_CALLBACK (on_entUser_changed), NULL);
  g_signal_connect ((gpointer) entGroup, "changed",
		    G_CALLBACK (on_entGroup_changed), NULL);
  g_signal_connect ((gpointer) step4_back, "clicked",
		    G_CALLBACK (on_step4_back_clicked), NULL);
  g_signal_connect ((gpointer) step4_next, "clicked",
		    G_CALLBACK (on_step4_next_clicked), NULL);
  g_signal_connect ((gpointer) step4_abort, "clicked",
		    G_CALLBACK (on_abort_clicked), NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (assi_step4, assi_step4, "assi_step4");
  GLADE_HOOKUP_OBJECT (assi_step4, vbox18, "vbox18");
  GLADE_HOOKUP_OBJECT (assi_step4, frame8, "frame8");
  GLADE_HOOKUP_OBJECT (assi_step4, vbox19, "vbox19");
  GLADE_HOOKUP_OBJECT (assi_step4, scrolledwindow8, "scrolledwindow8");
  GLADE_HOOKUP_OBJECT (assi_step4, textview12, "textview12");
  GLADE_HOOKUP_OBJECT (assi_step4, hseparator7, "hseparator7");
  GLADE_HOOKUP_OBJECT (assi_step4, table3, "table3");
  GLADE_HOOKUP_OBJECT (assi_step4, label110, "label110");
  GLADE_HOOKUP_OBJECT (assi_step4, entUser, "entUser");
  GLADE_HOOKUP_OBJECT (assi_step4, entGroup, "entGroup");
  GLADE_HOOKUP_OBJECT (assi_step4, label109, "label109");
  GLADE_HOOKUP_OBJECT (assi_step4, label101, "label101");
  GLADE_HOOKUP_OBJECT (assi_step4, hbuttonbox8, "hbuttonbox8");
  GLADE_HOOKUP_OBJECT (assi_step4, step4_back, "step4_back");
  GLADE_HOOKUP_OBJECT (assi_step4, alignment43, "alignment43");
  GLADE_HOOKUP_OBJECT (assi_step4, hbox70, "hbox70");
  GLADE_HOOKUP_OBJECT (assi_step4, image79, "image79");
  GLADE_HOOKUP_OBJECT (assi_step4, label102, "label102");
  GLADE_HOOKUP_OBJECT (assi_step4, step4_next, "step4_next");
  GLADE_HOOKUP_OBJECT (assi_step4, alignment48, "alignment48");
  GLADE_HOOKUP_OBJECT (assi_step4, hbox78, "hbox78");
  GLADE_HOOKUP_OBJECT (assi_step4, image84, "image84");
  GLADE_HOOKUP_OBJECT (assi_step4, label111, "label111");
  GLADE_HOOKUP_OBJECT (assi_step4, step4_abort, "step4_abort");
  GLADE_HOOKUP_OBJECT (assi_step4, alignment45, "alignment45");
  GLADE_HOOKUP_OBJECT (assi_step4, hbox72, "hbox72");
  GLADE_HOOKUP_OBJECT (assi_step4, image81, "image81");
  GLADE_HOOKUP_OBJECT (assi_step4, label104, "label104");

  return assi_step4;
}
